const allTeams = [
    { id: "4253", city: "台北", school: "台北美國學校", team: "Raid Zero" },
    { id: "6083", city: "嘉義", school: "協同中學", team: "Overlooking" },
    { id: "6191", city: "台北", school: "北一女", team: "RoboKryptonite" },
    { id: "6245", city: "嘉義", school: "協同中學", team: "Overlooking 2" },
    { id: "6947", city: "台北", school: "復興實中", team: "Savage Tumaz" },
    { id: "6998", city: "台南", school: "南科實中", team: "Unipards" },
    { id: "7130", city: "台中", school: "明道中學", team: "Future Shock" },
    { id: "7497", city: "台北", school: "成功高中", team: "MARAHO" },
    { id: "7526", city: "高雄", school: "雄中雄女聯隊", team: "Welcome to team" },
    { id: "7551", city: "嘉義", school: "竹崎高中", team: "Extreme Mechanism" },
    { id: "7589", city: "新北", school: "麗山高中", team: "Lishan Blue Magpie" },
    { id: "7632", city: "新北", school: "安康高中", team: "An Kang Robotics Maker" },
    { id: "7636", city: "台中", school: "中科實中", team: "Robomania" },
    { id: "7645", city: "台北", school: "南港高工", team: "NK MTC" },
    { id: "7673", city: "新北", school: "恆毅中學", team: "Formosan Sika" },
    { id: "7709", city: "台北", school: "板橋高中", team: "Formosa Pangolin" },
    { id: "8020", city: "台北", school: "建國中學", team: "CyberpunK" },
    { id: "8169", city: "高雄", school: "岡山高中", team: "Aries" },
    { id: "8503", city: "台北", school: "台北美國學校", team: "Raid One" },
    { id: "8569", city: "新北", school: "中和高中", team: "Zhonghe" },
    { id: "8584", city: "嘉義", school: "嘉華高中", team: "Infinity Robotics" },
    { id: "8585", city: "台北", school: "大安高工", team: "Bombax Leopard" },
    { id: "8595", city: "新北", school: "格致中學", team: "This Is How We Play" },
    { id: "8723", city: "桃園", school: "陽明中學", team: "Woodpanda" },
    { id: "8725", city: "新北", school: "南山高中", team: "MistyPanther" },
    { id: "8790", city: "台南", school: "中信國際學校", team: "Departure" },
    { id: "8805", city: "台南", school: "南光高中", team: "NKST36" },
    { id: "8806", city: "新北", school: "崇光中學", team: "Our Lady of Providence Dream League" },
    { id: "9079", city: "新北", school: "新店高中", team: "Mechanic storm" },
    { id: "9126", city: "高雄", school: "義大高中", team: "Silver Hawks" },
    { id: "9427", city: "新北", school: "樹林高中", team: "iDeer" },
    { id: "9501", city: "新北", school: "三民高中", team: "Sidereal Envoy" },
    { id: "9564", city: "新北", school: "泰山高中", team: "Taishan Robotics" },
    { id: "10034", city: "宜蘭", school: "慈心華德福實中", team: "GammaLand" },
    { id: "10114", city: "新北", school: "錦和高中", team: "Phantom Talons" },
    { id: "10390", city: "台中", school: "曉明女中", team: "GOOGIRL" },
    { id: "10922", city: "台北", school: "社區型隊伍", team: "Amped", rookie: true },
    { id: "11177", city: "新北", school: "新莊高中", team: "Hsin Chuang Senior High School FRC Team", rookie: true },
    { id: "11229", city: "高雄", school: "社區型隊伍", team: "Open Circuit", rookie: true },
    { id: "11313", city: "台中", school: "台中女中", team: "TCGS", rookie: true },
    { id: "11313", city: "台北", school: "開南商工", team: "KNHS Chelsea 11338", rookie: true }
];